# name of all AOC in the Bordeaux area
AOC = ['Barsac', 
       'Blaye', 
       'Bordeaux', 
       'Bordeaux supérieur', 
       'CadillacBon millésime',
       'Canon Fronsac', 
       'Cérons', 
       'Côtes de Blaye', 
       'Côtes de Bordeaux', 
       'Côtes de Bordeaux-St.-Macaire',
       'Côtes de Bourg, Bourg et Bourgeais', 
       'Crémant de Bordeaux', 
       'Entre-deux-Mers', 
       'Fronsac',
       'Graves', 
       'Graves de Vayres', 
       'Graves supérieures', 
       'Haut-Médoc', 
       'Lalande-de-Pomerol',
       'Listrac-Médoc', 
       'Loupiac', 
       'Lussac-St.-Emilion', 
       'Margaux', 'Médoc', 
       'Montagne-St.-Emilion',
       'Moulis', 
       'Neac', 
       'Pauillac', 
       'Pessac-Léognan', 
       'Pomerol', 
       'Premières Côtes de Bordeaux',
       'Puisseguin-St.-Emilion', 
       'St.-Emilion', 
       'St.-Emilion grand cru', 
       'St.-Estèphe', 
       'St.-Georges-St.-Emilion',
       'St.-Julien', 
       'Ste.-Croix-du-MontBon millésime', 
       'Ste.-Foy-Bordeaux', 
       'Sauternes', 
       'Côtes de Francs',
       'Côtes de Bourg', 'Listrac', 
       'Côtes de Castillon', 'Entre-Deux-Mers', 
       'Haut-Benauge', 
       'Cadillac',
       'Ste.-Croix-du-Mont', 
       'Vin de France', 
       'Vin de Table de France', 
       'Vin de Table Français', 
       'Bordeaux White'] 